name: Delete Branches After PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      # Step 3: Delete the branch if the PR was merged
      - name: Delete the branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            BRANCH_NAME=$(echo "${{ github.event.pull_request.head.ref }}")
            echo "Deleting branch: $BRANCH_NAME"
            gh api -X DELETE /repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME
          else
            echo "Pull request was not merged. No branch deletion."
          fi
