name: Push Docker Image to ECR Public repository

on:
  push:
    branches:
      - main

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (optional if you don't need repo files)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}    

      # Step 4: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: aws ecr-public get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_PUBLIC }}

      # Step 5: Pull the Docker image from Docker Hub
      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_REPO }}:4a91df2

      # Step 6: Tag the Docker image for ECR
      - name: Tag Docker image for ECR
        run: |
          docker tag ${{ secrets.DOCKER_REPO }}:4a91df2 ${{ secrets.ECR_PRIVATE_REPO }}:v1.0.0

      # Step 7: Push the Docker image to ECR
      - name: Push Docker image to ECR
        run: docker push ${{ secrets.ECR_PRIVATE_REPO }}:v1.0.0

      # Step 8: List ECR Repositories
      - name: List ECR Repositories
        run: |
          echo "Listing ECR repositories..."
          aws ecr-public describe-repositories --region ${{ secrets.AWS_REGION }}

      # Step 9: List Images in the Repository
      - name: List Images in ECR Repository
        run: |
          echo "Listing images in the ECR repository..."
          aws ecr-public list-images --repository-name ${{ secrets.AWS_ECR_PUBLIC_NAME }} --region ${{ secrets.AWS_REGION }}
