name: Terrafor Lint
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
env:
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#########################
jobs:
  tflint:
    if: ${{ !startswith(github.event.pull_request.head.ref, 'feat:') }}
    # Set the agent to run on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
